// @flow
import type { NextPage } from 'next';
import Head from 'next/head';
import { FormEvent, useEffect, useState } from 'react';
// import Image from 'next/image'
// import styles from '../styles/Home.module.css';
import SliderOver from '../components/SlideOver';
import NavBar from '../components/NavBar';

const Home: NextPage = () => {
  const [search, setSearch] = useState('');

  function handleSearch(e: FormEvent) {
    e.preventDefault();
    console.log('Search submited with: ', search);
  }
  useEffect(() => {
    console.log('loaded');
  }, []);

  return (
    <>
      <Head>
        <title>PDF Upload App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-full">
        <NavBar />
        <main>
          <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
            {/* Replace with your content */}
            <div className="px-4 py-6 sm:px-0">
              <div className="border-4 border-dashed border-gray-200 rounded-lg h-96">
                <h2>Or maybe this</h2>
                <p>Can i add multiple stuff here?</p>
                <SliderOver title="Fazer algo">
                  <span>Open Modal!</span>
                </SliderOver>
              </div>
            </div>
            {/* /End replace */}
          </div>
        </main>
        <footer>
          <span>Rodapé da página</span>
        </footer>
      </div>
    </>
  );
};

export default Home;
